env:
  es6: true
  node: true
  mocha: true
extends: [airbnb-base, "plugin:node/recommended", "plugin:security/recommended", "plugin:you-dont-need-lodash-underscore/compatible"]
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
	## Styling
	"indent": ["error", "tab"],
	"no-mixed-spaces-and-tabs": 1,
	"no-tabs": ["error", {"allowIndentationTabs": true}],
	"linebreak-style": "off",
	"max-len": "off",

	## Node specifics
	"node/exports-style": ["error", "module.exports"],
  "node/prefer-global/buffer": ["error", "always"],
  "node/prefer-global/console": ["error", "always"],
  "node/prefer-global/process": ["error", "always"],
  "node/prefer-global/url-search-params": ["error", "always"],
	"node/prefer-global/url": ["error", "always"],

  ## Requires
  "import/no-extraneous-dependencies": ["error", {"devDependencies": true, "optionalDependencies": false, "peerDependencies": false}]
}
