const swaggerJsdoc = require('swagger-jsdoc');

const options = {
	// List of files to be processed.
	// You should change this route
	apis: ['routes/*.yaml'],
	// You can also set globs for your apis
	// e.g. './routes/*.js'
	// basePath: '/',
	swaggerDefinition: {
		info: {
			description: 'API with autogenerated swagger doc',
			swagger: '2.0',
			title: 'your title here',
			version: '1.0.0',
		},
	},
};
const specs = swaggerJsdoc(options);
module.exports = specs;
